### ISSUE TITLE
small questions

### ISSUE THREAD

**Issue by scropion86** [EspLight/EspLight-firmware#1]
hello,

i like your entire project from kickstarter till now , i look at the schematic
![image](https://cloud.githubusercontent.com/assets/5569470/13313686/d0fb07ae-dbb0-11e5-9058-88974d236107.png)
i can see that you used L1 coil and that's for for what , sorry for such basic question i guess.
and is the CAPs should be 220uf.

and in firmware side is the ESP-12 stores the other data than the WIFI configuration in ROM or it will be lost after reset?

**Comment by michielbrink** [comment]
You can find the values at page 12 of
http://www.ti.com/lit/ds/symlink/lm2596.pdf
I hope this will helps you.
Only the config data is stored in flash

**Comment by Duality4Y** [comment]
that schematic is for the powersupply that chip is a switching powersupply chip, and it uses that coil to step down the voltage to appropriate values.
